// <auto-generated />
using System;
using LibraryEFCoreProj.LibraryContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryEFCoreProj.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250710221049_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryEFCoreProj.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "George Orwell"
                        },
                        new
                        {
                            AuthorId = 4,
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            AuthorId = 5,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            AuthorId = 6,
                            Name = "Stephen King"
                        },
                        new
                        {
                            AuthorId = 7,
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            AuthorId = 8,
                            Name = "Virginia Woolf"
                        },
                        new
                        {
                            AuthorId = 9,
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            AuthorId = 10,
                            Name = "Toni Morrison"
                        },
                        new
                        {
                            AuthorId = 11,
                            Name = "Charles Dickens"
                        },
                        new
                        {
                            AuthorId = 12,
                            Name = "Emily Brontë"
                        },
                        new
                        {
                            AuthorId = 13,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            AuthorId = 14,
                            Name = "Gabriel García Márquez"
                        },
                        new
                        {
                            AuthorId = 15,
                            Name = "Mark Twain"
                        },
                        new
                        {
                            AuthorId = 16,
                            Name = "Mary Shelley"
                        },
                        new
                        {
                            AuthorId = 17,
                            Name = "Ray Bradbury"
                        },
                        new
                        {
                            AuthorId = 18,
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            AuthorId = 19,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            AuthorId = 20,
                            Name = "Salman Rushdie"
                        });
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            PublicationYear = 1997,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            PublicationYear = 1998,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            PublicationYear = 1999,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            PublicationYear = 2000,
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1,
                            PublicationYear = 2003,
                            Title = "Harry Potter and the Order of the Phoenix"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 2,
                            PublicationYear = 1954,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 2,
                            PublicationYear = 1954,
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 2,
                            PublicationYear = 1955,
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 2,
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 2,
                            PublicationYear = 1977,
                            Title = "The Silmarillion"
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 3,
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 3,
                            PublicationYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 3,
                            PublicationYear = 1938,
                            Title = "Homage to Catalonia"
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 4,
                            PublicationYear = 1934,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 4,
                            PublicationYear = 1939,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 4,
                            PublicationYear = 1926,
                            Title = "The Murder of Roger Ackroyd"
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 4,
                            PublicationYear = 1937,
                            Title = "Death on the Nile"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 5,
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 5,
                            PublicationYear = 1811,
                            Title = "Sense and Sensibility"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 5,
                            PublicationYear = 1815,
                            Title = "Emma"
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 5,
                            PublicationYear = 1817,
                            Title = "Persuasion"
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 6,
                            PublicationYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 6,
                            PublicationYear = 1986,
                            Title = "It"
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 6,
                            PublicationYear = 1974,
                            Title = "Carrie"
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 6,
                            PublicationYear = 1987,
                            Title = "Misery"
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 7,
                            PublicationYear = 1951,
                            Title = "Foundation"
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 7,
                            PublicationYear = 1952,
                            Title = "Foundation and Empire"
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 7,
                            PublicationYear = 1953,
                            Title = "Second Foundation"
                        },
                        new
                        {
                            BookId = 29,
                            AuthorId = 7,
                            PublicationYear = 1950,
                            Title = "I, Robot"
                        },
                        new
                        {
                            BookId = 30,
                            AuthorId = 8,
                            PublicationYear = 1925,
                            Title = "Mrs Dalloway"
                        },
                        new
                        {
                            BookId = 31,
                            AuthorId = 8,
                            PublicationYear = 1927,
                            Title = "To the Lighthouse"
                        },
                        new
                        {
                            BookId = 32,
                            AuthorId = 8,
                            PublicationYear = 1928,
                            Title = "Orlando"
                        },
                        new
                        {
                            BookId = 33,
                            AuthorId = 8,
                            PublicationYear = 1931,
                            Title = "The Waves"
                        },
                        new
                        {
                            BookId = 34,
                            AuthorId = 9,
                            PublicationYear = 1952,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            BookId = 35,
                            AuthorId = 9,
                            PublicationYear = 1929,
                            Title = "A Farewell to Arms"
                        },
                        new
                        {
                            BookId = 36,
                            AuthorId = 9,
                            PublicationYear = 1940,
                            Title = "For Whom the Bell Tolls"
                        },
                        new
                        {
                            BookId = 37,
                            AuthorId = 10,
                            PublicationYear = 1987,
                            Title = "Beloved"
                        },
                        new
                        {
                            BookId = 38,
                            AuthorId = 10,
                            PublicationYear = 1977,
                            Title = "Song of Solomon"
                        },
                        new
                        {
                            BookId = 39,
                            AuthorId = 10,
                            PublicationYear = 1992,
                            Title = "Jazz"
                        },
                        new
                        {
                            BookId = 40,
                            AuthorId = 11,
                            PublicationYear = 1859,
                            Title = "A Tale of Two Cities"
                        },
                        new
                        {
                            BookId = 41,
                            AuthorId = 11,
                            PublicationYear = 1861,
                            Title = "Great Expectations"
                        },
                        new
                        {
                            BookId = 42,
                            AuthorId = 11,
                            PublicationYear = 1838,
                            Title = "Oliver Twist"
                        },
                        new
                        {
                            BookId = 43,
                            AuthorId = 12,
                            PublicationYear = 1847,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            BookId = 44,
                            AuthorId = 13,
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 45,
                            AuthorId = 13,
                            PublicationYear = 1934,
                            Title = "Tender is the Night"
                        },
                        new
                        {
                            BookId = 46,
                            AuthorId = 14,
                            PublicationYear = 1967,
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            BookId = 47,
                            AuthorId = 14,
                            PublicationYear = 1985,
                            Title = "Love in the Time of Cholera"
                        },
                        new
                        {
                            BookId = 48,
                            AuthorId = 15,
                            PublicationYear = 1876,
                            Title = "The Adventures of Tom Sawyer"
                        },
                        new
                        {
                            BookId = 49,
                            AuthorId = 15,
                            PublicationYear = 1884,
                            Title = "Adventures of Huckleberry Finn"
                        },
                        new
                        {
                            BookId = 50,
                            AuthorId = 16,
                            PublicationYear = 1818,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            BookId = 51,
                            AuthorId = 16,
                            PublicationYear = 1826,
                            Title = "The Last Man"
                        },
                        new
                        {
                            BookId = 52,
                            AuthorId = 17,
                            PublicationYear = 1953,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            BookId = 53,
                            AuthorId = 17,
                            PublicationYear = 1950,
                            Title = "The Martian Chronicles"
                        },
                        new
                        {
                            BookId = 54,
                            AuthorId = 18,
                            PublicationYear = 1865,
                            Title = "War and Peace"
                        },
                        new
                        {
                            BookId = 55,
                            AuthorId = 18,
                            PublicationYear = 1877,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            BookId = 56,
                            AuthorId = 19,
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 57,
                            AuthorId = 20,
                            PublicationYear = 1981,
                            Title = "Midnight’s Children"
                        },
                        new
                        {
                            BookId = 58,
                            AuthorId = 20,
                            PublicationYear = 1988,
                            Title = "Satanic Verses"
                        },
                        new
                        {
                            BookId = 59,
                            AuthorId = 1,
                            PublicationYear = 2007,
                            Title = "Harry Potter and the Deathly Hallows"
                        },
                        new
                        {
                            BookId = 60,
                            AuthorId = 1,
                            PublicationYear = 2012,
                            Title = "The Casual Vacancy"
                        },
                        new
                        {
                            BookId = 61,
                            AuthorId = 2,
                            PublicationYear = 2007,
                            Title = "Children of Hurin"
                        },
                        new
                        {
                            BookId = 62,
                            AuthorId = 3,
                            PublicationYear = 1936,
                            Title = "Keep the Aspidistra Flying"
                        },
                        new
                        {
                            BookId = 63,
                            AuthorId = 4,
                            PublicationYear = 1936,
                            Title = "The ABC Murders"
                        },
                        new
                        {
                            BookId = 64,
                            AuthorId = 5,
                            PublicationYear = 1814,
                            Title = "Mansfield Park"
                        },
                        new
                        {
                            BookId = 65,
                            AuthorId = 6,
                            PublicationYear = 1975,
                            Title = "Salem’s Lot"
                        },
                        new
                        {
                            BookId = 66,
                            AuthorId = 7,
                            PublicationYear = 1954,
                            Title = "The Caves of Steel"
                        },
                        new
                        {
                            BookId = 67,
                            AuthorId = 8,
                            PublicationYear = 1929,
                            Title = "A Room of One’s Own"
                        },
                        new
                        {
                            BookId = 68,
                            AuthorId = 9,
                            PublicationYear = 1926,
                            Title = "The Sun Also Rises"
                        },
                        new
                        {
                            BookId = 69,
                            AuthorId = 10,
                            PublicationYear = 1997,
                            Title = "Paradise"
                        },
                        new
                        {
                            BookId = 70,
                            AuthorId = 11,
                            PublicationYear = 1850,
                            Title = "David Copperfield"
                        },
                        new
                        {
                            BookId = 71,
                            AuthorId = 12,
                            PublicationYear = 1847,
                            Title = "Agnes Grey"
                        },
                        new
                        {
                            BookId = 72,
                            AuthorId = 13,
                            PublicationYear = 1920,
                            Title = "This Side of Paradise"
                        },
                        new
                        {
                            BookId = 73,
                            AuthorId = 14,
                            PublicationYear = 1981,
                            Title = "Chronicle of a Death Foretold"
                        },
                        new
                        {
                            BookId = 74,
                            AuthorId = 15,
                            PublicationYear = 1881,
                            Title = "The Prince and the Pauper"
                        },
                        new
                        {
                            BookId = 75,
                            AuthorId = 16,
                            PublicationYear = 1819,
                            Title = "Mathilda"
                        },
                        new
                        {
                            BookId = 76,
                            AuthorId = 17,
                            PublicationYear = 1962,
                            Title = "Something Wicked This Way Comes"
                        },
                        new
                        {
                            BookId = 77,
                            AuthorId = 18,
                            PublicationYear = 1899,
                            Title = "Resurrection"
                        },
                        new
                        {
                            BookId = 78,
                            AuthorId = 19,
                            PublicationYear = 2015,
                            Title = "Go Set a Watchman"
                        },
                        new
                        {
                            BookId = 79,
                            AuthorId = 20,
                            PublicationYear = 1983,
                            Title = "Shame"
                        },
                        new
                        {
                            BookId = 80,
                            AuthorId = 1,
                            PublicationYear = 2005,
                            Title = "Harry Potter and the Half-Blood Prince"
                        },
                        new
                        {
                            BookId = 81,
                            AuthorId = 2,
                            PublicationYear = 2017,
                            Title = "Beren and Lúthien"
                        },
                        new
                        {
                            BookId = 82,
                            AuthorId = 3,
                            PublicationYear = 1939,
                            Title = "Coming Up for Air"
                        },
                        new
                        {
                            BookId = 83,
                            AuthorId = 4,
                            PublicationYear = 1941,
                            Title = "Evil Under the Sun"
                        },
                        new
                        {
                            BookId = 84,
                            AuthorId = 5,
                            PublicationYear = 1817,
                            Title = "Northanger Abbey"
                        },
                        new
                        {
                            BookId = 85,
                            AuthorId = 6,
                            PublicationYear = 2013,
                            Title = "Doctor Sleep"
                        },
                        new
                        {
                            BookId = 86,
                            AuthorId = 7,
                            PublicationYear = 1957,
                            Title = "The Naked Sun"
                        },
                        new
                        {
                            BookId = 87,
                            AuthorId = 8,
                            PublicationYear = 1933,
                            Title = "Flush"
                        },
                        new
                        {
                            BookId = 88,
                            AuthorId = 9,
                            PublicationYear = 1950,
                            Title = "Across the River and Into the Trees"
                        },
                        new
                        {
                            BookId = 89,
                            AuthorId = 10,
                            PublicationYear = 1981,
                            Title = "Tar Baby"
                        },
                        new
                        {
                            BookId = 90,
                            AuthorId = 11,
                            PublicationYear = 1853,
                            Title = "Bleak House"
                        },
                        new
                        {
                            BookId = 91,
                            AuthorId = 12,
                            PublicationYear = 1848,
                            Title = "The Tenant of Wildfell Hall"
                        },
                        new
                        {
                            BookId = 92,
                            AuthorId = 13,
                            PublicationYear = 1922,
                            Title = "The Beautiful and Damned"
                        },
                        new
                        {
                            BookId = 93,
                            AuthorId = 14,
                            PublicationYear = 1975,
                            Title = "The Autumn of the Patriarch"
                        },
                        new
                        {
                            BookId = 94,
                            AuthorId = 15,
                            PublicationYear = 1889,
                            Title = "A Connecticut Yankee in King Arthur’s Court"
                        },
                        new
                        {
                            BookId = 95,
                            AuthorId = 16,
                            PublicationYear = 1823,
                            Title = "Valperga"
                        },
                        new
                        {
                            BookId = 96,
                            AuthorId = 17,
                            PublicationYear = 1957,
                            Title = "Dandelion Wine"
                        },
                        new
                        {
                            BookId = 97,
                            AuthorId = 18,
                            PublicationYear = 1886,
                            Title = "The Death of Ivan Ilyich"
                        },
                        new
                        {
                            BookId = 98,
                            AuthorId = 20,
                            PublicationYear = 1999,
                            Title = "The Ground Beneath Her Feet"
                        },
                        new
                        {
                            BookId = 99,
                            AuthorId = 11,
                            PublicationYear = 1854,
                            Title = "Hard Times"
                        },
                        new
                        {
                            BookId = 100,
                            AuthorId = 20,
                            PublicationYear = 1995,
                            Title = "The Moor’s Last Sigh"
                        });
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Borrower", b =>
                {
                    b.Property<int>("BorrowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("BorrowerId");

                    b.ToTable("Borrowers", (string)null);

                    b.HasData(
                        new
                        {
                            BorrowerId = 1,
                            Name = "Alice Smith"
                        },
                        new
                        {
                            BorrowerId = 2,
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            BorrowerId = 3,
                            Name = "Carol Williams"
                        },
                        new
                        {
                            BorrowerId = 4,
                            Name = "David Brown"
                        },
                        new
                        {
                            BorrowerId = 5,
                            Name = "Emma Davis"
                        },
                        new
                        {
                            BorrowerId = 6,
                            Name = "Frank Wilson"
                        },
                        new
                        {
                            BorrowerId = 7,
                            Name = "Grace Taylor"
                        },
                        new
                        {
                            BorrowerId = 8,
                            Name = "Henry Moore"
                        },
                        new
                        {
                            BorrowerId = 9,
                            Name = "Isabella Clark"
                        },
                        new
                        {
                            BorrowerId = 10,
                            Name = "James Lee"
                        },
                        new
                        {
                            BorrowerId = 11,
                            Name = "Katherine Adams"
                        },
                        new
                        {
                            BorrowerId = 12,
                            Name = "Liam Harris"
                        },
                        new
                        {
                            BorrowerId = 13,
                            Name = "Mia Lewis"
                        },
                        new
                        {
                            BorrowerId = 14,
                            Name = "Noah Walker"
                        },
                        new
                        {
                            BorrowerId = 15,
                            Name = "Olivia Young"
                        },
                        new
                        {
                            BorrowerId = 16,
                            Name = "Peter Allen"
                        },
                        new
                        {
                            BorrowerId = 17,
                            Name = "Quinn Baker"
                        },
                        new
                        {
                            BorrowerId = 18,
                            Name = "Rachel Carter"
                        },
                        new
                        {
                            BorrowerId = 19,
                            Name = "Samuel Evans"
                        },
                        new
                        {
                            BorrowerId = 20,
                            Name = "Tara Green"
                        });
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Borrowing", b =>
                {
                    b.Property<int>("BorrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowingId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowingId");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowerId");

                    b.ToTable("Borrowings", (string)null);

                    b.HasData(
                        new
                        {
                            BorrowingId = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 1
                        },
                        new
                        {
                            BorrowingId = 2,
                            BookId = 1,
                            BorrowDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 2,
                            ReturnDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 3,
                            BookId = 2,
                            BorrowDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 3
                        },
                        new
                        {
                            BorrowingId = 4,
                            BookId = 3,
                            BorrowDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 4,
                            ReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 5,
                            BookId = 4,
                            BorrowDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 5
                        },
                        new
                        {
                            BorrowingId = 6,
                            BookId = 5,
                            BorrowDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 6,
                            ReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 7,
                            BookId = 6,
                            BorrowDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 7
                        },
                        new
                        {
                            BorrowingId = 8,
                            BookId = 7,
                            BorrowDate = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 8,
                            ReturnDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 9,
                            BookId = 8,
                            BorrowDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 9
                        },
                        new
                        {
                            BorrowingId = 10,
                            BookId = 9,
                            BorrowDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 10,
                            ReturnDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 11,
                            BookId = 10,
                            BorrowDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 11
                        },
                        new
                        {
                            BorrowingId = 12,
                            BookId = 11,
                            BorrowDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 12,
                            ReturnDate = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 13,
                            BookId = 12,
                            BorrowDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 13
                        },
                        new
                        {
                            BorrowingId = 14,
                            BookId = 13,
                            BorrowDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 14,
                            ReturnDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 15,
                            BookId = 14,
                            BorrowDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 15
                        },
                        new
                        {
                            BorrowingId = 16,
                            BookId = 15,
                            BorrowDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 16,
                            ReturnDate = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 17,
                            BookId = 16,
                            BorrowDate = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 17
                        },
                        new
                        {
                            BorrowingId = 18,
                            BookId = 17,
                            BorrowDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 18,
                            ReturnDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 19,
                            BookId = 18,
                            BorrowDate = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 19
                        },
                        new
                        {
                            BorrowingId = 20,
                            BookId = 19,
                            BorrowDate = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 20,
                            ReturnDate = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 21,
                            BookId = 20,
                            BorrowDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 1
                        },
                        new
                        {
                            BorrowingId = 22,
                            BookId = 21,
                            BorrowDate = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 2,
                            ReturnDate = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 23,
                            BookId = 22,
                            BorrowDate = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 3
                        },
                        new
                        {
                            BorrowingId = 24,
                            BookId = 23,
                            BorrowDate = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 4,
                            ReturnDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 25,
                            BookId = 24,
                            BorrowDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 5
                        },
                        new
                        {
                            BorrowingId = 26,
                            BookId = 25,
                            BorrowDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 6,
                            ReturnDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 27,
                            BookId = 26,
                            BorrowDate = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 7
                        },
                        new
                        {
                            BorrowingId = 28,
                            BookId = 27,
                            BorrowDate = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 8,
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 29,
                            BookId = 28,
                            BorrowDate = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 9
                        },
                        new
                        {
                            BorrowingId = 30,
                            BookId = 29,
                            BorrowDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 10,
                            ReturnDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 31,
                            BookId = 30,
                            BorrowDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 11
                        },
                        new
                        {
                            BorrowingId = 32,
                            BookId = 31,
                            BorrowDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 12,
                            ReturnDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 33,
                            BookId = 32,
                            BorrowDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 13
                        },
                        new
                        {
                            BorrowingId = 34,
                            BookId = 33,
                            BorrowDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 14,
                            ReturnDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 35,
                            BookId = 34,
                            BorrowDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 15
                        },
                        new
                        {
                            BorrowingId = 36,
                            BookId = 35,
                            BorrowDate = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 16,
                            ReturnDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 37,
                            BookId = 36,
                            BorrowDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 17
                        },
                        new
                        {
                            BorrowingId = 38,
                            BookId = 37,
                            BorrowDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 18,
                            ReturnDate = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 39,
                            BookId = 38,
                            BorrowDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 19
                        },
                        new
                        {
                            BorrowingId = 40,
                            BookId = 39,
                            BorrowDate = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 20,
                            ReturnDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 41,
                            BookId = 40,
                            BorrowDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 1
                        },
                        new
                        {
                            BorrowingId = 42,
                            BookId = 41,
                            BorrowDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 2,
                            ReturnDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 43,
                            BookId = 42,
                            BorrowDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 3
                        },
                        new
                        {
                            BorrowingId = 44,
                            BookId = 43,
                            BorrowDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 4,
                            ReturnDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 45,
                            BookId = 44,
                            BorrowDate = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 5
                        },
                        new
                        {
                            BorrowingId = 46,
                            BookId = 45,
                            BorrowDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 6,
                            ReturnDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 47,
                            BookId = 46,
                            BorrowDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 7
                        },
                        new
                        {
                            BorrowingId = 48,
                            BookId = 47,
                            BorrowDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 8,
                            ReturnDate = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 49,
                            BookId = 48,
                            BorrowDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 9
                        },
                        new
                        {
                            BorrowingId = 50,
                            BookId = 49,
                            BorrowDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 10,
                            ReturnDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 51,
                            BookId = 50,
                            BorrowDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 11
                        },
                        new
                        {
                            BorrowingId = 52,
                            BookId = 51,
                            BorrowDate = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 12,
                            ReturnDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 53,
                            BookId = 52,
                            BorrowDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 13
                        },
                        new
                        {
                            BorrowingId = 54,
                            BookId = 53,
                            BorrowDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 14,
                            ReturnDate = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 55,
                            BookId = 54,
                            BorrowDate = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 15
                        },
                        new
                        {
                            BorrowingId = 56,
                            BookId = 55,
                            BorrowDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 16,
                            ReturnDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 57,
                            BookId = 56,
                            BorrowDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 17
                        },
                        new
                        {
                            BorrowingId = 58,
                            BookId = 57,
                            BorrowDate = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 18,
                            ReturnDate = new DateTime(2025, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowingId = 59,
                            BookId = 58,
                            BorrowDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 19
                        },
                        new
                        {
                            BorrowingId = 60,
                            BookId = 59,
                            BorrowDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowerId = 20,
                            ReturnDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Book", b =>
                {
                    b.HasOne("LibraryEFCoreProj.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Borrowing", b =>
                {
                    b.HasOne("LibraryEFCoreProj.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryEFCoreProj.Models.Borrower", "Borrower")
                        .WithMany("Borrowings")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Borrower");
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Book", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryEFCoreProj.Models.Borrower", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
